{
 "title": "Infrastructure",
 "tags": [
  "coescd",
  "infrastructure"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Infra Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=~\"postgres_exporter|redis_exporter|nats|prometheus|nginx\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Container Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"docker\"}"
    }
   ]
  }
 ]
}